name:                mig-rio
version:             0.1.0.0
github:              "anton-k/mig"
license:             BSD3
author:              "Anton Kholomiov"
maintainer:          "anton.kholomiov@gmail.com"
copyright:           "2023 Anton Kholomiov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Utils to use RIO with mig library
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Utils to use mig with rio library

language: GHC2021

default-extensions:
  - DerivingStrategies

dependencies:
- base >= 4.7 && < 5
- mig-server
- rio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
