name:                mig-rio
version:             0.1.0.1
github:              "anton-k/mig"
license:             BSD3
author:              "Anton Kholomiov"
maintainer:          "anton.kholomiov@gmail.com"
copyright:           "2023 Anton Kholomiov"
license-file:        LICENSE

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Utils to use RIO with mig library
description:         Utils to use RIO with mig library. Provides instance for HasServer class.
category:            Web

language: GHC2021

default-extensions:
  - DerivingStrategies

dependencies:
- base >= 4.7 && < 5
- mig-server >= 0.1.0.1
- rio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
