name:                mig-postgresql-simple
version:             0.1.0.0
github:              "githubuser/mig-postgresql-simple"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mig-postgresql-simple#readme>

language: GHC2021

default-extensions:
  - OverloadedStrings
  - OverloadedRecordDot
  - DuplicateRecordFields
  - LambdaCase
  - DerivingStrategies
  - StrictData
  - AllowAmbiguousTypes
  - RecordWildCards

dependencies:
- base >= 4.7 && < 5
- postgresql-simple
- mig-tools
- bytestring
- aeson
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
