name:                mig-wai
version:             0.1.1.0
github:              "anton-k/mig"
license:             BSD3
author:              "Anton Kholomiov"
maintainer:          "anton.kholomiov@gmail.com"
copyright:           "2023 Anton Kholomiov"
license-file:        LICENSE

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Render mig-servers as wai-applications
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:   Library to render mig-servers as WAI-applications.

language: GHC2021

default-extensions:
  - OverloadedRecordDot
  - DuplicateRecordFields
  - OverloadedStrings
  - LambdaCase

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- mig >= 0.2.1.0
- text
- wai
- exceptions
- data-default

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
