.PHONY: build test run

build:
	stack build

test:
	stack test

run:
	stack run route-args-mig-example-app
	
run-hello-wrold:
	stack run hello-world-mig-example-app	

run-route-args:
	stack run route-args-mig-example-app

run-counter:
	stack run counter-mig-example-app

run-json-api:
	stack run json-api-mig-example-app

run-html:
	stack run html-mig-example-app
