resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/6.yaml

packages:
- .

extra-deps:
  - ../../mig
  - ../../mig-client
  - ../../mig-server
  - ../../mig-swagger-ui
  - ../../mig-wai
  - ../../mig-extra
  - ../../mig-tools
  - ../../tools/mig-fast-logger
