on: [push]
name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y liblzma-dev

      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v5
