on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack-version: ['3.9.3']
        include:
          - os: ubuntu-latest
            stack-args: "--system-ghc"
          - os: macos-latest
            stack-args: "--system-ghc"
#          - os: windows-latest
#            stack-args: ""
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y liblzma-dev
      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.stack-root }}
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'package.yaml') }}
          restore-keys: ${{ runner.os }}-stack-

      - name: Build and test
        run: |
          stack build --test ${{ matrix.stack-args }}
