on: [push]
name: "build examples"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-action@v5
        with:
          working-directory: ./examples/mig-example-apps
